### ISSUE TITLE
Working example of simple conversion of WAV stream to FLAC stream

### ISSUE THREAD

**Issue by jasonxz** [EntangledBits/CUETools.Codecs#1]
The example on the front page doesn't seem to work as the constructor for the WAVReader is invalid.
I have the Wave in a stream and I want to compress using FLAC to another stream.

**Comment by pkoelbl** [comment]
Invalid as VS says it doesn't exist or Invalid as it throws an error?

**Comment by jasonxz** [comment]
My bad....this was a namespace issue.  Apparently I am referencing multiple projects that contain a WAVReader class.

**Comment by pkoelbl** [comment]
Ok let me know if anything else comes up, I originally used this on a xamarin project.
